---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thape_web_dev

test:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST", nil) %>
  database: <%= ENV.fetch("POSTGRES_DB", 'thape_web_test') %>
  username: <%= ENV.fetch("POSTGRES_USER", nil) %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", nil) %>

production:
  <<: *default
  database: thape_web_prod

tianhua2019:
  adapter: sqlite3
  timeout: 5000
  database: db/tianhua2019.sqlite3
