---
default: &default
  corpid: <%= Rails.application.credentials.wechat_corpid! %>
  corpsecret: <%= Rails.application.credentials.wechat_corpsecret! %>
  agentid: <%= Rails.application.credentials.wechat_agentid! %>
  token: <%= Rails.application.credentials.wechat_token! %>
  access_token: "tmp/wechat_access_token"
  encrypt_mode: true
  encoding_aes_key: <%= Rails.application.credentials.wechat_encoding_aes_key! %>
  jsapi_ticket: "tmp/wechat_jsapi_ticket"

production:
  <<: *default

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default

# Multiple Accounts
hulaquan_development:
  appid: <%= Rails.application.credentials.wechat_hulaquan_appid! %>
  secret: <%= Rails.application.credentials.wechat_hulaquan_secret! %>
  token: <%= Rails.application.credentials.wechat_hulaquan_token! %>
  encrypt_mode: true
  access_token: "tmp/wechat_hulaquan_dev_access_token"
  encoding_aes_key: <%= Rails.application.credentials.wechat_hulaquan_encoding_aes_key! %>

hulaquan_test:
  appid: <%= Rails.application.credentials.wechat_hulaquan_appid! %>
  secret: <%= Rails.application.credentials.wechat_hulaquan_secret! %>
  token: <%= Rails.application.credentials.wechat_hulaquan_token! %>
  encrypt_mode: true
  access_token: "tmp/wechat_hulaquan_test_access_token"
  encoding_aes_key: <%= Rails.application.credentials.wechat_hulaquan_encoding_aes_key! %>

hulaquan_production:
  appid: <%= Rails.application.credentials.wechat_hulaquan_appid! %>
  secret: <%= Rails.application.credentials.wechat_hulaquan_secret! %>
  token: <%= Rails.application.credentials.wechat_hulaquan_token! %>
  encrypt_mode: true
  access_token: "tmp/wechat_hulaquan_access_token"
  encoding_aes_key: <%= Rails.application.credentials.wechat_hulaquan_encoding_aes_key! %>

# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
